### PR TITLE
fix: Revert of banks in FmodBankLoader UI now works

### LINKED ISSUE #278: Reset to default Fmod banks on FmodBankLoader causes crash by playing any event, restarting the engine is needed
Add-on Version: Release 4.3.0-4.2.2
Engine: Godot v4.3.stable.official [77dcf97d8]
Running on Windows 11.

By resetting the banks list on the FmodBankLoader using the reset to default button glitches the node, and by trying to play any event crashes the game, restarting the engine is needed to fixed. I note that, the ( + ) and ( - ) buttons works fine for editing the Banks list.

image

https://github.com/user-attachments/assets/f9ee006b-3320-4e66-8a67-18b6e6804b61

On video, when I click on the reset to default button and set the bank again, the rest button not shows up, strange, but idk

### PR DESCRIPTION
**Pull request by piiertho**
This resolves #278

### CODE REVIEW

File: src/nodes/fmod_bank_loader.cpp [hunk 1]
```diff
@@ -27,14 +29,31 @@ const Array& FmodBankLoader::get_bank_paths() const {
     return bank_paths;
 }
 
+bool FmodBankLoader::_property_can_revert(const StringName& p_property) const {
+    if (p_property == StringName(bank_path_property_name)) {
```
Comment (CedNaru) [inline src/nodes/fmod_bank_loader.cpp:33]: Nitpick, but I'd rather have the StringName stored in a FmodStringName singleton, like Godot does internally, instead of hashing/instantiating it every single call (which the Godot editor calls for every property of an object each time the inspector is refreshed).

(The singleton has to be initialized and destroyed alongside the extension lifecycle or Godot will complain about StringName leaks).

**Review by CedNaru — APPROVED** [review]
